# Generated by Django 4.0.5 on 2022-07-06 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='phone',
        ),
    ]
