# Generated by Django 4.0.5 on 2022-07-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('asunto', models.CharField(max_length=100)),
                ('createat', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField()),
                ('updateat', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
